include_recipe "dev-machine::editors"
include_recipe "dev-machine::git"
include_recipe "dev-machine::php"
include_recipe "dev-machine::golang"
include_recipe "dev-machine::node"
include_recipe "dev-machine::terminal"
